<?php

Route::middleware('web')
    ->namespace('Shuramita\Article\Controllers')
    ->group(function()
    {
        Route::group(['prefix' => 'admin','middleware' => ['auth','admin']], function () {
            Route::get('article',['as'=>'admin_list_articles','uses'=>'ArticleController@index']);
            Route::get('article/create',['as'=>'admin_create_article','uses'=>'ArticleController@create']);
            Route::get('article/edit/{id}',['as'=>'admin_edit_article','uses'=>'ArticleController@edit']);
        });
        Route::group(['prefix' => 'admin','middleware' => ['auth','admin']], function () {
            Route::get('article/category',['as'=>'admin_list_articles_categories','uses'=>'CategoryController@index']);
            Route::get('article/category/create',['as'=>'admin_create_articles_category','uses'=>'CategoryController@create']);
            Route::get('article/category/edit/{id}',['as'=>'admin_edit_articles_category','uses'=>'CategoryController@edit']);
        });
    });
Route::middleware(['auth:api'])
    ->namespace('Shuramita\Article\Controllers\API')
    ->prefix('api/article')
    ->group(function () {
    Route::post('create', 'ArticleController@create')->name('api_create_new_article');
    Route::post('update', 'ArticleController@update')->name('api_update_article');
    Route::post('delete/{id}', 'ArticleController@delete')->name('api_delete_article');
});
Route::middleware(['auth:api','admin'])
    ->namespace('Shuramita\Article\Controllers\API')
    ->prefix('api/category')
    ->group(function () {
        Route::post('create', 'CategoryController@create')->name('api_create_new_category');
        Route::post('update', 'CategoryController@update')->name('api_update_category');
        Route::post('delete/{id}', 'CategoryController@delete')->name('api_delete_category');
});
// generated by script
Route::middleware('web')
    ->namespace('Shuramita\Article\Controllers')
    ->group(function()
    {
        Route::group(['prefix' => 'admin','middleware' => ['auth','admin']], function () {
            Route::get('fuck',['as'=>'admin_list_fucks','uses'=>'FuckController@index']);
            Route::get('fuck/create',['as'=>'admin_create_fuck','uses'=>'FuckController@create']);
            Route::get('fuck/edit/{id}',['as'=>'admin_edit_fuck','uses'=>'FuckController@edit']);
        });
    });
Route::middleware(['auth:api'])
    ->namespace('Shuramita\Article\Controllers\API')
    ->prefix('api/fuck')
    ->group(function () {
        Route::post('create', 'FuckController@create')->name('api_create_new_fuck');
        Route::post('update', 'FuckController@update')->name('api_update_fuck');
        Route::post('delete/{id}', 'FuckController@delete')->name('api_delete_fuck');
});
// end generated by script
